import React from 'react'
import Image from 'next/image'
import { NotFoundImage } from '@/icons'
import { EmptyBox } from '@/icons';

type Props = {}

const NotFound = (props: Props) => {
  return (
    <div className='flex flex-col min-h-[70vh] w-full justify-center items-center gap-12'>
        <Image src={EmptyBox} alt='not-found' />
        <div className='flex flex-col items-center justify-center text-center'>
            <p className='text-3xl font-semibold text-primary'>
                Nothing to see here
            </p>
            <p className='text-base font-normal text-secondary'>
                So here is a random image generated by <span className='text-slide-genius'>Creative AI</span>
            </p>
        </div>
    </div>
  )
}

export default NotFound